# General
title: Leo
description: "A teenagers view on web development and intuitive UI design."

author: Leonard Lamprecht
email: lamprechtleonard@gmail.com
url: http://leo.github.io
google_verify: epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o

# Social
twitter: lmprht
github: leo

# Build
markdown: kramdown
kramdown:
    input: GFM
sass:
    style: :compressed

#Other
permalink: /blog/:title
timezone: DE
include: [ 'robots.txt' ]
exclude: [ 'LICENSE', 'README.md', 'CNAME', 'vendor', 'Gemfile' ]
gems:
    - jekyll-sitemap
    
compress_html:
    ingore:
        envs: [ 'test' ]