# General
name: Leo Lamprecht
description: A teenagers view on web development and intuitive UI design.
url: http://leo.im

# Build
sass:
  style: :compressed

exclude: ['_posts', 'Gemfile*', 'CNAME', '*.md']
