# General
title: Leo
description: "A one-man-show about great software, hosted by a 17-year-old developer."

author: Leonard Lamprecht
email: lamprechtleonard@gmail.com
url: http://leo.github.io
google_verify: epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o

# Social
twitter: lmprht
github: leo

# Build
markdown: kramdown
kramdown:
    input: GFM
sass:
    style: :compressed

#Other
permalink: /blog/:title
timezone: DE
include: [ 'robots.txt' ]
exclude: [ 'LICENSE', 'README.md', 'CNAME' ]
gems:
    - jekyll-sitemap
    - jemoji